### ISSUE TITLE
Ability to delete a phase

### ISSUE THREAD

**Issue by jrweakland** [Esri/military-planner-application-csharp#31]
A user will want to be able to delete a phase of an operation if that phase was not approved by the commander.

**Comment by jmccausland** [comment]
This was added in v0.5.0

**Comment by csmoore** [comment]
@jmccausland - just a process note - when an issue is ready to verify change the label to "Verify" and Assign it to the originator (Jim in this case) to test/verify & close.

I'll do this to this issue as an example, & you can do to the others you updated today.

**Comment by csmoore** [comment]
Assigning to @jrweakland to verify&close

**Comment by jrweakland** [comment]
Verified.
