### ISSUE TITLE
Preserve window position and size

### ISSUE THREAD

**Issue by garys-esri** [Esri/military-planner-application-csharp#39]
Currently the application window always opens at the same size. A more advanced solution would be to remember the window position and size when the application closes and use that position and size next time the app runs. That seems to be what many Windows applications do.

**Comment by jmccausland** [comment]
This was added in v0.5.0

**Comment by jmccausland** [comment]
Assigning to @jrweakland to verify&close

**Comment by jrweakland** [comment]
verified
