### ISSUE TITLE
Update to Current Runtime Version (10.2.5), add automated build, and unit testing

### ISSUE THREAD

**Issue by csmoore** [Esri/military-planner-application-csharp#40]
Some open items from the repo review that are larger tasks

- [x] Update to Current AGS .NET Runtime Released Version (10.2.5)
- [x] Add msbuild configuration / steps
- [x] Add unit tests and steps

See https://github.com/Esri/solutions-widgets-wpf if you need an example

**Comment by jmccausland** [comment]
v0.6.0 has been updated to use ArcGIS Runtime SDK .NET 10.2.5

**Comment by jrweakland** [comment]
@jmccausland - Will you be working on the last two items in this issue?

**Comment by jmccausland** [comment]
Fixed with pull request #61
