### ISSUE TITLE
Ability to edit polygon vertices after the polygon is created

### ISSUE THREAD

**Issue by jrweakland** [Esri/military-planner-application-csharp#50]
As a user I would like the ability to edit the vertices of a polygon after I have created the polygon. Currently, I have to delete the polygon and recreate it.

**Comment by jmccausland** [comment]
This was added in release v0.5.0

**Comment by jmccausland** [comment]
Assigning to @jrweakland to verify&close

**Comment by jrweakland** [comment]
Verified.
