### ISSUE TITLE
Retained information from a saved mission

### ISSUE THREAD

**Issue by jrweakland** [Esri/military-planner-application-csharp#51]
As a user I would expect that when I load a saved mission that the information for the mission would automatically appear in the Phase Information area.

![image](https://cloud.githubusercontent.com/assets/5739155/6715071/5835f402-cd59-11e4-9f94-e206f099f7ce.png)

Right now I have to select the <b>Edit</b> button and the select <b>OK</b> for the phase information to appear from the save mission file.

![image](https://cloud.githubusercontent.com/assets/5739155/6715114/9f052c72-cd59-11e4-982f-a2870522bff5.png)

**Comment by jmccausland** [comment]
This is fixed in release v0.5.0

**Comment by jrweakland** [comment]
Reviewed
