### ISSUE TITLE
Problems when app was closed while minimized on previous run

### ISSUE THREAD

**Issue by garys-esri** [Esri/military-planner-application-csharp#53]
Make a mission XML file if you don't have one.

Run the app. It displays fine. Minimize the app, right-click it in the Windows taskbar, and choose **Close window**. The app closes.

Run the app again. This time it starts minimized. Restore or maximize it, and the map is blank. Instead, the map should display. Now try to load a mission XML file, and the app crashes. Instead, it should either load the mission properly or handle a failure gracefully.

**Comment by jmccausland** [comment]
Fixed with pull request #61
