### ISSUE TITLE
Phase label blocks Add, Back, Next buttons when app window is narrow

### ISSUE THREAD

**Issue by garys-esri** [Esri/military-planner-application-csharp#55]
Run the app and adjust the window width so that the Add, Back, and/or Next buttons are underneath the phase label in the upper left corner of the map. Try to click those buttons, and you can't because the phase label blocks them.

In this situation, the phase label isn't very readable anyway, so perhaps the button bar should be over the label.

Workaround: adjust the width so the buttons are not underneath the phase label.

**Comment by jmccausland** [comment]
Fixed with pull request #61
