### ISSUE TITLE
Published EXE not work

### ISSUE THREAD

**Issue by sabri-ghaith** [Esri/military-planner-application-csharp#64]
I downloaded the zip file, re-created the expired license and used the ArcGISRuntime.dll V10.2.7.
The app running with no issues, but if i publish and try to open the output after setup, it does not work. (to verify the source of the problem, I created another sample app and i can publish and open exe file with no issues)

Could you help in this please?

**Comment by jmccausland** [comment]
can  you give more detailed steps to reproduce the problem?  Thanks

**Comment by sabri-ghaith** [comment]
Hi jmccausland,

My environment is Win7 64 bit

1. Open VS2013
2. Open the extracted MilitaryPlanner solution
3. Delete Esri.ArcGISRuntime from refrences (because it is not referenced)
4. Add Esri.ArcGISRuntime v10.2.7 to the project
5. Delete old certificate because it is expired
6. Create new test certificate
7. Build succeeded
8. Run and test functionalities
9. Publish
10. Run setup.exe
11. Run MilitaryPlanner.application
12. Unkown error (see attached)

![image](https://cloud.githubusercontent.com/assets/18396688/14453238/44b5c048-009c-11e6-868e-4b3dd90251df.png)


P.S.: If I create a new ArcGIS Runtime SDK 10.2.5 for WPF project and publish it, it worked.


Thanks,

**Comment by jmccausland** [comment]
This repo hasn't been updated for 10.2.7.  You might be able to modify the MilitaryPlanner.exe.manifest file to update the runtime version in a txt editor and then run the MilitaryPlanner.exe.

**Comment by jmccausland** [comment]
Updated project for ArcGIS Runtime 10.2.7

**Comment by sabri-ghaith** [comment]
Thanks for your reply, I'll test and get back to you.
