### ISSUE TITLE
Adding text

### ISSUE THREAD

**Issue by shantaramkamath** [Esri/military-planner-application-csharp#67]
Hello,

I wanted to add text (using TextSymbol) on message layer with every symbol added on the map. Please let me know how to go about this.

Thanks,
Sam

**Comment by csmoore** [comment]
The labels are built into the military symbols so you would just need to set these properties. I am not familiar with this code but it would likely be at the same place that Symbol Id Code "sic" "sidc" is set. Here is a list of the military label properties for 2525C: https://github.com/Esri/military-features-data/tree/master/data/mil2525c#modifier-label-fields

**Comment by garys-esri** [comment]
Ditto what @csmoore said. If I were you, I would use `additionalinformation` to display arbitrary text with a symbol. Set it in the same place that you set `sic`.

**Comment by shantaramkamath** [comment]
Thank you very much for your replies. I'm able to add text to symbols using additionalinformation and staffcomments properties. Though not every symbol can display the text added using the above properties except some categories of symbols. But that might be natural behavior of military symbols, as text might not be required for all symbols. Thanks again. Regards.
-Sam

**Comment by garys-esri** [comment]
@shantaramkamath: I'm glad you got it working! Feel free to close the issue if you now have the information you need.
