### ISSUE TITLE
Adding text to OOB symbols

### ISSUE THREAD

**Issue by shantaramkamath** [Esri/military-planner-application-csharp#70]
Hello,

Is it possible to add text to OOB symbols? If yes, How should I go about it?

Thanks in advance.

-Sam

**Comment by garys-esri** [comment]
What do you mean by OOB symbols? As discussed in #67, you can set several text fields on military symbols.

**Comment by shantaramkamath** [comment]
OOB means Order Of Battle i guess. There are few Infantry F symbols in this, which are not part of 2525C symbol library. I wanted to know if text can be added to these OOB symbols as well.

**Comment by garys-esri** [comment]
Can you share the code you're using to render non-2525C symbols? Maybe that will help someone give you advice on how to add text. I think you'll probably need to use a second graphic with a `TextSymbol` but that depends on how you're displaying the symbol.

**Comment by shantaramkamath** [comment]
Closing this issue.
