### ISSUE TITLE
Adding Line Of Sight Tool functionality

### ISSUE THREAD

**Issue by shantaramkamath** [Esri/military-planner-application-csharp#71]
Hello,

I've added Line of sight functionality to this application. I've done the following:
1) Created an output using Line of sight tool in Arcmap 10.3.1
2) Shared the result from above activity, as a service on ArcGis for server.
3) Wrote a piece of code to consume this service and get the ouput. 
I'm getting the correct output, but I'm struggling to show the output correctly. Could you please help me to show the output correctly for Line of Sight? Could you point me to some code already available?

I've searched on internet and not able to find the code specific for showing output of Line of Sight.

Thanks,
Sam

**Comment by csmoore** [comment]
I have not done this, but it may be similar to the Vehicle Commander sample that calls a GP Tool which returns a ArcGISDynamicMapServiceLayer (which is then added to the map)

https://github.com/Esri/vehicle-commander-java/blob/master/source/VehicleCommander/src/com/esri/vehiclecommander/view/ViewshedJPanel.java#L50
