### ISSUE TITLE
Military Symbology 

### ISSUE THREAD

**Issue by shantaramkamath** [Esri/military-planner-application-csharp#72]
Hello,

Can I use modifiers fields from Symbol Dictionary to change the symbols at runtime? For example to convert an Infantry to Platoon or Squad, etc.? 
Because currently Company, Platoon,Squad, etc are separate symbols in this application and to create a Squad, for example, I have to add Infantry symbol and on top of this infantry symbol, I also need to add Squad symbol, which makes Squad created by me as two different symbols. But I want Squad as a single symbol. 
I think one of the modifiers fields mentioned in below link can be used for this purpose.
https://github.com/Esri/military-features-data/tree/master/data/mil2525c#modifier-label-fields

Please let me know how should I go about this?

Regards,
Sam

**Comment by csmoore** [comment]
The modifier attributes in the 10.2.X mil2525c dictionary renderer only control the labels,

To set the properties that control the symbol display (like echelon), you would need to change the value of the Symbol ID Code ("sic" field/property).

Here is an overview of the SIDC format: http://webhelp.esri.com/arcgisdesktop/9.1/body.cfm?tocVisable=1&TopicName=Symbol%20ID%20code 
And the actual -2525 docs are available at:
http://quicksearch.dla.mil/qsDocDetails.aspx?ident_number=114934  

One additional note: the current release of Pro (and next release of runtime) does allow you to set these [as individual attributes](https://github.com/Esri/military-features-data/tree/v.next/data/mil2525d/core_data/gdbs#graphic-display-amplifiers) , but the old/original dictionaryrenderer released at Runtime 10.2.X did not yet have this capability.

**Comment by csmoore** [comment]
Again, I'm not familiar with this particular app, but in general you would use the base SIC returned from the symbol search (Ex. "Infantry F (sic = SFGPUCI---)" ) and add the other 5 characters (the 2 modifier characters and "---" will work).  

Ex: symbol "sic" attribute = 
"SFGPUCI---" + "-D" + "---"

One Note: the last time I used the WPF runtime (several years ago) - it was returning a 15 character SIC from the search: https://github.com/Esri/military-features-data/blob/master/test/WpfRuntime/SidcSymbolViewer/MainWindow.xaml.cs#L40

**Comment by shantaramkamath** [comment]
Hello Chris,

Thank you for answering my query.
Just wanted to inform you that I'm not using WPF runtime but I'm using .NET runtime SDK (I believe there is separate sdk for wpf). ArcGIS runtime SDK for .Net returns 10 character SIC. I'll try to append 5 characters at the end of SIC, as suggested by you and see if it works.

Thanks,
Sam

**Comment by csmoore** [comment]
Unfortunately there were several small inconsistencies like this between the various runtime SDKs - this should be resolved in the next release of the Runtime SDK (Quartz)

**Comment by shantaramkamath** [comment]
I tried to download the Quartz beta, but it failed several times after downloading 132MB. Can I use Quartz beta with this application?

**Comment by csmoore** [comment]
Probably not - the API has changed considerably and I don't believe is backward compatible.

Another issue with the beta is that it only supports the latest version of the standard (-2525D) which also is not backward compatible and changes the SIC/SIDC format considerably (from -2525C). 2525C/B Change 2 won't be added until final release.

You may want to contact your distributor about the download issue in case you do want to try it out.

**Comment by shantaramkamath** [comment]
Does that mean current runtime SDK doesn't support 2525D?

**Comment by csmoore** [comment]
Its a little confusing, mainly because the timing of the release of 2525D - hopefully this clarifies:

Runtime 10.2.X - did not support 2525D , only mil2525c
Runtime Quartz Beta - only 2525D
Runtime Quartz - 2525D, 2525C, 2525Bc2

**Comment by shantaramkamath** [comment]
I hope Runtime Quartz Beta will return a 15 character SIC unlike current runtime sdk. 
Also isn't there any other way to provide the end user of this application to create for example, Infantry Platoon (sic = SFGPUCI----D), at runtime?

**Comment by csmoore** [comment]
At 10.2.X - it requires the full SIC/SIDC (sic = `SFGPUCI----D---` in this case). At Quartz, it should be easier to set these as individual attributes.

**Comment by shantaramkamath** [comment]
I would appreciate your advice on the following workaround for this issue:-
What if I create a group layer of say Infantry and Platoon symbols to make an Infantry Platoon, as nothing else seems to work with ArcGIS runtime SDK 10.2.7? What problems could I face by using this workaround?

**Comment by csmoore** [comment]
Setting the full 15-character SIC (attribute "sic" => "SFGPUCI----D---") on a MessageProcessor or GraphicsLayer symbol should work.

For this particular application it looks like you could readily test/verify this just by adding some additional entries to https://github.com/Esri/military-planner-application-csharp/blob/master/source/MilitaryPlanner/data/oob/oobexample.xml

**Comment by shantaramkamath** [comment]
When will new SDK (Quartz) released?

**Comment by csmoore** [comment]
I haven't seen any official release date - and only know what has been posted publically: Ex: https://geonet.esri.com/thread/175384 but the 2525D standard does work in the current beta and has several samples: https://blogs.esri.com/esri/arcgis/2016/07/07/working-with-mil-std-2525d-symbology-using-quartz-runtime/
